<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>vttk_auto.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\vttk-auto.Domain\vttk-auto.Domain.csproj" />
    </ItemGroup>

</Project>
